// Auto-generated from dict/aee_codes.yml
// DO NOT EDIT - Run 'npm run build:codes' to regenerate

/**
 * AEE (Agro EDI Europe) code mappings
 * Source: spec/daplos2024-fp-v09-5.md
 * Version: 0.95
 */

/**
 * Unified AEE codes dictionary
 * Contains all code categories with their code→label mappings
 */
export const AEE_CODES = {
  "input_nature": {
    "ZIU": "Herbicide",
    "ZIV": "Fongicide",
    "ZIW": "Insecticide",
    "ZIX": "Molluscicide / hélicide",
    "ZIY": "Nématicide",
    "ZIZ": "Régulateur",
    "ZJA": "Divers (huiles)",
    "ZJB": "Effluents d'élevage",
    "ZJC": "Fertilisation minérale",
    "ZJD": "Fertirrigation",
    "ZJE": "Irrigation",
    "ZJF": "Semence",
    "ZJG": "Traitement de semence",
    "ZJJ": "Acaricides",
    "ZJK": "Bactéricides",
    "ZJL": "Moyens biologiques",
    "ZJN": "Rodenticides",
    "ZJO": "Taupicides",
    "ZJP": "Corvicides",
    "ZJQ": "Corvifuges",
    "ZJR": "Répulsifs oiseaux-gibiers",
    "ZJS": "Substance de croissance",
    "ZJT": "Plants",
    "ZKA": "Sous-produits et déchets issus de filières alimentaires",
    "ZKB": "Sous-produits et déchets issus de filières non alimentaires",
    "ZKC": "Boues résiduaires de station d'épuration et de compost urbain",
    "U64": "Boues résiduaires de station d'épuration et de compost d'industrie",
    "ZKD": "Fertilisation minérale type Bulk",
    "ZQG": "Adjuvants",
    "ZSU": "Fertilisation organo-minérale",
    "ZMT": "Inhibiteurs de germination",
    "ZKE": "Amendements calco-magnésiens",
    "U60": "Eléments fertilisants préconisés",
    "U61": "BIOCIDE",
    "U62": "Stimulateur des défenses naturelles"
  },
  "organic_input": {
    "SCA": "Fumier de bovins",
    "SCB": "Lisiers de bovins",
    "SCC": "Purin de bovins",
    "SCD": "Fumier de porcins",
    "SCE": "Lisier de porcins",
    "SCF": "Fumier d'ovins",
    "SCG": "Lisier d'ovins",
    "SCH": "Fumier de caprins",
    "SCI": "Lisier de caprins",
    "SCJ": "Fumier de chevaux",
    "SCK": "Fumier de dindes",
    "SCL": "Fientes de dinde",
    "SCM": "Lisier de dindes",
    "SCN": "Lisier de canards",
    "SCO": "Fumier de canards",
    "SCP": "Lisier de pintades",
    "SCQ": "Fientes de pintades",
    "SCR": "Fumier de pintades",
    "SCS": "Fientes de poules pondeuses",
    "SCT": "Fumier de poules pondeuses",
    "SCZ": "Lisier de poules pondeuses",
    "SCU": "Fumier de poulets de chair",
    "SCV": "Fientes fraîches de poulets de chair",
    "SCW": "Lisier de poulets de chair",
    "SCY": "Lisier de lapins",
    "SDA": "Vinasses de betteraves",
    "SDB": "Ecumes de sucreries",
    "SDC": "Fumier de champignons",
    "SDD": "Lombricompost",
    "SDE": "Tourbe",
    "SDF": "Refus de tamisage fumier de porc",
    "SDG": "Soluble de pomme de terre",
    "SDH": "Marc de raisin",
    "SDI": "Compost de déchet vert",
    "SDJ": "Autres sous produits et déchets issus des filières alimentaires",
    "SDK": "Carbonate de Calcium",
    "SDL": "Boue d'épuration",
    "SDQ": "Effluents viticoles",
    "SDR": "Compost urbain",
    "SDS": "Autres boues résiduaires de station d'épuration et de compost urbain",
    "SDT": "Terre de récupération",
    "SDU": "Eaux de lavage",
    "SDV": "Eaux de lavage produits terreux",
    "SDW": "Eaux de lavage produits non terreux",
    "SDX": "Autres sous-produits et déchets de filières non alimentaires",
    "SDY": "Boues de papeterie",
    "ZOK": "Lisier de veau"
  },
  "calco_magnesian": {
    "U01": "Craie",
    "U02": "Maërl",
    "U03": "Marne",
    "U04": "Dolomie",
    "SDK": "Carbonate de Calcium",
    "U05": "Carbonate de magnésium",
    "U06": "Chaux vive",
    "U07": "Chaux éteinte",
    "U08": "Chaux calcique",
    "U09": "Chaux magnésienne",
    "U10": "Chaux calco-magnésienne",
    "U11": "Amendement calcique mixte",
    "U12": "Amendement magnésien mixte",
    "SDB": "Ecumes de sucrerie",
    "U14": "Amendement basique sidérurgique",
    "U15": "Craie broyée",
    "U16": "Craie phosphatée",
    "U17": "Coquilles d'œufs",
    "U18": "Autre amendement calco-magnésien"
  },
  "effluent_qualifier": {
    "SJA": "pur",
    "SJB": "dilué",
    "SJC": "très dilué (non couvert)",
    "SJD": "très pailleux",
    "SJE": "composté sec",
    "SJF": "composté humide",
    "SJG": "pas de compost",
    "SJH": "engraissement",
    "SJI": "litière accumulée",
    "SJJ": "litière raclée",
    "SJK": "mous de logette",
    "SJL": "étable entravée",
    "SJM": "pente paillée",
    "SJN": "alimentation classique",
    "SJO": "alimentation biphase",
    "SJP": "paille",
    "SJQ": "sciure",
    "SJR": "copeaux",
    "SJS": "% Matière sèche",
    "SJT": "label (oui/non)",
    "SJU": "chaulée (oui/non)",
    "SJV": "origine urbaine",
    "SKA": "origine papeterie",
    "SKB": "origine laiterie",
    "SKC": "abattoir",
    "SKD": "brut",
    "SKE": "centrifugé",
    "SKF": "humides",
    "SKG": "préséchées",
    "SKH": "séchées",
    "SKI": "avant stockage",
    "SKJ": "après stockage conditions humides",
    "SKK": "après stockage conditions sèches",
    "SKL": "frais",
    "SKM": "mûr",
    "SKN": "Solide",
    "SKO": "liquide",
    "SKP": "Compact",
    "U51": "Digestat brut",
    "U52": "Digestat liquide",
    "U53": "Digestat solide"
  },
  "seed_qualifier": {
    "ZQB": "Non OGM",
    "ZQC": "OGM",
    "ZQA": "Semences certifiées",
    "ZQD": "Semences de ferme",
    "ZQE": "Génération G0",
    "ZQF": "Génération G1",
    "ZQG": "Génération G2",
    "ZQH": "Génération G3",
    "ZQI": "Génération G4",
    "ZQJ": "Génération R1",
    "ZQK": "Génération R2",
    "ZQL": "Génération R3",
    "U50": "Semences non certifiées"
  },
  "technical_characteristics": {
    "ZJ2": "Calibre",
    "ZJ3": "PMG (Poids de Mille Grains)",
    "ZJ4": "Humidité",
    "ZJ5": "PS (Poids Spécifique)",
    "ZJ6": "Taux d'impuretés",
    "ZJ7": "Taux de Protéines",
    "ZJ8": "Calibrage",
    "ZJ9": "Taux de MS",
    "ZK1": "Taux de nitrates"
  },
  "units": {
    "CMT": "Centimètres",
    "DOS": "Dose (intrants)",
    "GRA": "Grain",
    "HAR": "Hectares (code AEE)",
    "KGM": "Kilogramme (intrants)",
    "KGT": "KG/T",
    "LTR": "Litre (intrant)",
    "LTT": "L/T",
    "MTQ": "Metre cube",
    "MMT": "Millimètres (intrants)",
    "NAR": "Unité (grain, plants, capsule, diffuseur) (intrants)",
    "PCD": "Pourcentage",
    "PLT": "Plant",
    "TNE": "Tonnes",
    "W95": "g/l",
    "W96": "Pourcentage de volume",
    "W97": "sans unité",
    "ZHL": "m3 / ha (que pour l'amendement organique)",
    "ZIT": "Degrés Celsius",
    "ZKK": "Litre / ha",
    "ZKL": "Kilogramme / ha",
    "ZKM": "Dose / ha",
    "ZKN": "Unité / ha (grain, plants, capsules)"
  },
  "crop_species": {
    "E01": "Abricotier",
    "E02": "Achillée millefeuille",
    "E03": "Agrostide blanche",
    "E04": "Agrostide des chiens",
    "E05": "Agrostide jouet du vent",
    "E06": "Agrostide montana",
    "E07": "Agrostide stolonifère",
    "E08": "Aigremoine",
    "E09": "Ail des ours",
    "E10": "Ail rocambole",
    "E11": "Alchémille",
    "E12": "Alliaire",
    "E13": "Alpiste roseau",
    "E14": "Amandier",
    "E15": "Amaranthe",
    "E16": "Ambérique = pousse de soja",
    "E17": "Ananas",
    "E18": "Ancolie",
    "E19": "Anémone",
    "E20": "Aneth",
    "E21": "Angelique",
    "E22": "Anis",
    "E23": "Argousier",
    "E24": "Armoise",
    "E25": "Arnica",
    "E26": "Aunée",
    "E27": "Avocatier",
    "E28": "Avoine brésilienne",
    "E29": "Avoine byzantine",
    "E30": "Avoine jaunâtre",
    "E31": "Avoine nue",
    "E32": "Ballote",
    "E33": "Balsamite",
    "E34": "Bananier",
    "E35": "Bardane",
    "E36": "Basilic",
    "E37": "Belladone",
    "E38": "Benoîte",
    "E39": "Bouillon blanc (molène)",
    "E40": "Bourrache",
    "E41": "Brome biebersteinii",
    "E42": "Brome carinatus",
    "E43": "Brome cathartique",
    "E44": "Brome dressé",
    "E45": "Brome faux-seigle",
    "E46": "Brome fibreux",
    "E47": "Brome inerme",
    "E48": "Brome mou",
    "E49": "Brome sitchensis",
    "E50": "Brome stérile",
    "E51": "Brunelle vulgaire",
    "E52": "Bugle rampant",
    "E53": "Buplèvre",
    "E54": "Cameline",
    "E55": "Camomille",
    "E56": "Capucine",
    "E57": "Caroube",
    "E58": "Carthame",
    "E59": "Carvi",
    "E60": "Caseiller",
    "E61": "Cataire ou Chataire",
    "E62": "Centaurée bleuet",
    "E63": "Centaurée d'Espagne",
    "E64": "Centaurée du solstice",
    "E65": "Centaurée jacée",
    "E66": "Centaurée scabieuse",
    "E67": "Cerisier",
    "E68": "Chardon",
    "E69": "Chataigner",
    "E70": "Chayotte - Christophine",
    "E71": "Chelidoine",
    "E72": "Chénopode",
    "E73": "Chiendent à crête",
    "E74": "Chiendent à tige courte",
    "E75": "Chiendent du désert",
    "E76": "Chiendent rampant",
    "E77": "Chiendent velu",
    "E78": "Chou marin",
    "E79": "Christe marine",
    "E80": "Chrysanthème",
    "E81": "Ciboule",
    "E82": "Ciboulette",
    "E83": "Citronnier",
    "E84": "Clarkia",
    "E85": "Clémentinier",
    "E86": "Cognassier",
    "E87": "Consoude",
    "E88": "Coriandre",
    "E89": "Coton",
    "E90": "Courge",
    "E91": "Crambe d'abbyssinie",
    "E92": "Cresson alénois",
    "E93": "Cresson de terre",
    "E94": "Cresson des fontaines",
    "E95": "Crosne",
    "E96": "Cumin",
    "E97": "Dahlia",
    "E98": "Dauphinelle à grandes fleurs",
    "E99": "Dictame de crête",
    "F01": "Digitale",
    "F02": "Dimorphoteca",
    "F03": "Echalion",
    "F04": "Echinacée",
    "F05": "Eglantier",
    "F06": "Epilobe à 4 angles",
    "F07": "Eschscholtzia",
    "F08": "Estragon",
    "F09": "Eupatoire",
    "F10": "Euphraise",
    "F11": "Feijoa",
    "F12": "Fenugrec",
    "F13": "Fétuque hétérophylle",
    "F14": "Fétuque ovine",
    "F15": "Fétuque rouge",
    "F16": "Ficaire",
    "F17": "Figuier",
    "F18": "Fléole bulbeuse",
    "F19": "Fruit de la passion",
    "F20": "Fumeterre",
    "F21": "Gaillet",
    "F22": "Garance",
    "F23": "Genêt",
    "F24": "Gentiane",
    "F25": "Ginkgo biloba",
    "F26": "Glaïeul – Acidanthera",
    "F27": "Goyavier",
    "F28": "Grand Mélilot",
    "F29": "Grande cigüe",
    "F30": "Grindelia",
    "F31": "Hamamelis",
    "F32": "Hysope",
    "F33": "Igname",
    "F34": "Immortelle",
    "F35": "Iris",
    "F36": "Ispaghul ou plantain des indes",
    "F37": "Jasmin",
    "F38": "Jujubier",
    "F39": "Jusquiame noire",
    "F40": "Kaki    (Plaqueminier)",
    "F41": "Kenaf",
    "F42": "Kiwi (Actinidia)",
    "F43": "Kiwi jaune",
    "F44": "Lamier Blanc (Ortie Blanche)",
    "F45": "Laser gallicum",
    "F46": "Laurier",
    "F47": "Lavande",
    "F48": "Lavatère",
    "F49": "Lespedeza capitata",
    "F50": "Lin vivace",
    "F51": "Litchi",
    "F52": "Liveche",
    "F53": "Lotier des marais",
    "F54": "Mandarinier",
    "F55": "Manguier",
    "F56": "Marjolaine",
    "F57": "Marrube blanc",
    "F58": "Matricaire",
    "F59": "Matricaire camomille",
    "F60": "Mauve",
    "F61": "Mélange Floristique",
    "F62": "Mélange Pollinique",
    "F63": "Mélilot blanc",
    "F64": "Mélilot officinal",
    "F65": "Mélisse",
    "F66": "Menthe",
    "F67": "Menyanthe",
    "F68": "Millet perlé",
    "F69": "Miscanthus",
    "F70": "Monarde",
    "F71": "Moutarde épinard",
    "F72": "Mûrier (Arbuste)",
    "F73": "Mûrier (Ronce)",
    "F74": "Muscari",
    "F75": "Myosotis",
    "F76": "Myosotis hybride",
    "F77": "Myosotis sylvatica",
    "F78": "Myrthe ou myrte",
    "F79": "Myrtille et airelles",
    "F80": "Nashi",
    "F81": "Nèfle du Japon",
    "F82": "Néflier d'Europe",
    "F83": "Noisetier",
    "F84": "Noyer",
    "F85": "Œillet d'Inde",
    "F86": "Olivier",
    "F87": "Onagre",
    "F88": "Oranger",
    "F89": "Origan",
    "F90": "Ortie",
    "F91": "Oseille",
    "F92": "Oxalis petite-oseille",
    "F93": "Pamplemoussier (pomelo)",
    "F94": "Panais",
    "F95": "Panic érigé (switch grass)",
    "F96": "Passiflore",
    "F97": "Pastel",
    "F98": "Patate douce",
    "F99": "Pâtisson",
    "G01": "Pâturin ampla",
    "G02": "Pâturin annuel",
    "G03": "Pâturin comprimé",
    "G04": "Pâturin des bois",
    "G05": "Pâturin des marais",
    "G06": "Pavot de Californie",
    "G07": "Pêcher",
    "G08": "Pensée",
    "G09": "Phalaris",
    "G10": "Piloselle",
    "G11": "Piment",
    "G12": "Pimprenelle",
    "G13": "Pissenlit",
    "G14": "Pistachier",
    "G15": "Plantain lancéolé",
    "G16": "Plantain majeur",
    "G17": "Plantain psyllium",
    "G18": "Plaqueminier (Kaki)",
    "G19": "Plumcot",
    "G20": "Poirier",
    "G21": "Pommier",
    "G22": "Potentille",
    "G23": "Potiron",
    "G24": "Pourpier",
    "G25": "Prêle",
    "G26": "Primevère",
    "G27": "Prunellier",
    "G28": "Prunier",
    "G29": "Pyrethre",
    "G30": "Raifort",
    "G31": "Ray-grass annuel",
    "G32": "Reine des prés",
    "G33": "Reine marguerite",
    "G34": "Renoncule",
    "G35": "Renouée",
    "G36": "Renouée à feuilles de Patience",
    "G37": "Renouée des oiseaux",
    "G38": "Renouée liseron",
    "G39": "Renouée persicaire",
    "G40": "Romarin",
    "G41": "Roquette",
    "G42": "Rose d'Inde",
    "G43": "Rosier",
    "G44": "Sainfoin d'Espagne",
    "G45": "Salicaire",
    "G46": "Sarrasin de Tartarie",
    "G47": "Sarriette des jardins",
    "G48": "Sarriette vivace",
    "G49": "Sauge officinale",
    "G50": "Sauge sclarée",
    "G51": "Scabieuse",
    "G52": "Scorsonère",
    "G53": "Scrofulaire",
    "G54": "Scutellaire",
    "G55": "Seigle forestier",
    "G56": "Solidage",
    "G57": "Souci",
    "G58": "Sureau",
    "G59": "Sisymbre",
    "G60": "Tagete",
    "G61": "Tanaisie = chrysanthème",
    "G62": "Thym",
    "G63": "Tilleul",
    "G64": "Topinambour",
    "G65": "Trèfle aggloméré",
    "G66": "Trèfle bardane",
    "G67": "Trèfle fraise",
    "G68": "Trèfle hérissé",
    "G69": "Trèfle renversé",
    "G70": "Trèfle souterrain",
    "G71": "Trèfle strié",
    "G72": "Tritonia",
    "G73": "Vanille",
    "G74": "Véronique",
    "G75": "Véronique à fleurs de gentiane",
    "G76": "Véronique en épi",
    "G77": "Verveine officinale",
    "G78": "Vesce à quatre graines",
    "G79": "Vesce de Narbonne",
    "G80": "Vesce hérissée",
    "G81": "Vesce jaune",
    "G82": "Violette",
    "G83": "Vipérine faux plantain",
    "G84": "Vulnéraire",
    "G85": "Vulpin des champs",
    "G86": "Vulpin des prés",
    "G87": "Vulpin genouille",
    "G88": "Zinnia",
    "H67": "Centaurée",
    "H68": "Lotier",
    "I05": "Canne à sucre",
    "J01": "Cultures fruitières",
    "J02": "Cultures légumières",
    "J10ZAQZFA": "blé dur de printemps",
    "J10ZAQZFB": "blé dur d'hiver",
    "J10ZARZFA": "blé tendre de printemps",
    "J10ZARZFB": "blé tendre d'hiver",
    "ZA2": "Betterave sucrière",
    "ZAF": "Agrostide",
    "ZAG": "Ail",
    "ZAH": "Arbres à noyaux",
    "ZAI": "Arbres à pépins",
    "ZAJ": "Artichaut",
    "ZAK": "Asperge",
    "ZAL": "Aubergine",
    "ZAM": "Avoine",
    "ZAN": "Betterave fourragère",
    "ZAO": "Betterave rouge",
    "ZAP": "Brocoli",
    "ZAQ": "Blé dur",
    "ZAR": "Blé tendre",
    "ZAS": "Céléri",
    "ZAT": "Brome",
    "ZAU": "Cardon",
    "ZAV": "Carotte",
    "ZAW": "Cassis",
    "ZAX": "Céleri",
    "ZAY": "Cerfeuil",
    "ZAZ": "Chanvre",
    "ZBA": "Chicorée",
    "ZBB": "Choux",
    "ZBC": "Choux fourrager",
    "ZBD": "Choux-fleur",
    "ZBE": "Colza",
    "ZBF": "Concombre",
    "ZBG": "Coquelicot",
    "ZBH": "Cornichon",
    "ZBI": "Courgette",
    "ZBJ": "Dactyle",
    "ZBK": "Echalote",
    "ZBL": "Endive",
    "ZBM": "Epeautre",
    "ZBN": "Epinard",
    "ZBO": "Fenouil",
    "ZBP": "Festullolium",
    "ZBQ": "Fétuque élevée",
    "ZBR": "Fétuque des prés",
    "ZBS": "Fève",
    "ZBT": "Fèverole",
    "ZBU": "Fléole",
    "ZBV": "Fraise",
    "ZBW": "Framboise",
    "ZBX": "Friche",
    "ZBY": "Fromental (avoine élevée)",
    "ZBZ": "Groseille",
    "ZCA": "Haricot sec (graines)",
    "ZCB": "Haricot vert",
    "ZCC": "Houblon",
    "ZCD": "Jachère autre semée",
    "ZCE": "Jachère en crucifères",
    "ZCF": "Jachère en graminées",
    "ZCG": "Jachère en légumineuses et en graminées",
    "ZCH": "Jachère en légumineuses",
    "ZCJ": "Laitue",
    "ZCK": "Lentilles",
    "ZCL": "Lin",
    "ZCM": "Lotier cornicule",
    "ZCN": "Lupin blanc",
    "ZCO": "Lupin jaune",
    "ZCP": "Lupin bleu",
    "ZCQ": "Luzerne",
    "ZCR": "Mâche",
    "ZCS": "Maïs",
    "ZCU": "Mélange graminées protéagineux",
    "ZCV": "Mélilot",
    "ZCW": "Melon",
    "ZCX": "Millepertuis",
    "ZCY": "Minette (syn: Luzerne lupuline)",
    "ZCZ": "Moha",
    "ZDA": "Moutarde blanche",
    "ZDB": "Moutarde brune",
    "ZDC": "Moutarde noire",
    "ZDD": "Navet",
    "ZDE": "Navette",
    "ZDF": "Oeillette",
    "ZDG": "Oignon",
    "ZDH": "Orge",
    "ZDI": "Paturin des prés",
    "ZDJ": "Paturin commun",
    "ZDK": "Persil",
    "ZDL": "Phacélie",
    "ZDM": "Piment",
    "ZDN": "Poireau",
    "ZDO": "Pois protéagineux",
    "ZDP": "Pois de conserve",
    "ZDQ": "Pois chiche",
    "ZDR": "Poivron",
    "ZDS": "Pomme de terre",
    "ZDT": "Potiron",
    "ZDU": "Prairie",
    "ZDV": "Radis",
    "ZDW": "Radis fourrager",
    "ZDX": "Ray grass anglais",
    "ZDY": "Ray grass hybride",
    "ZDZ": "Ray grass italie",
    "ZEA": "Riz",
    "ZEB": "Rutabaga",
    "ZEC": "Sainfouin",
    "ZED": "Salsifis",
    "ZEH": "Sarrazin",
    "ZEJ": "Seigle",
    "ZEK": "Serradelle",
    "ZEL": "Soja",
    "ZEM": "Spergule",
    "ZEN": "Tabac",
    "ZFA": "Orge de printemps 2 rangs",
    "ZFB": "Orge d'hiver 2 rangs",
    "ZMA": "Tomate",
    "ZMB": "Tournesol",
    "ZMC": "Trèfle violet",
    "ZMD": "Trèfle blanc",
    "ZME": "Trèfle inarnat",
    "ZMF": "Trèfle hybride",
    "ZMG": "Trèfle alexandrie",
    "ZMH": "Trèfle de Perse",
    "ZMI": "Triticale",
    "ZMJ": "Valériane",
    "ZMK": "Vesce commune",
    "ZML": "Vesce de Cerdagne",
    "ZMM": "Vesce de Panonie",
    "ZMN": "Vesce velue",
    "ZMO": "Vigne",
    "ZND": "Pastèque",
    "ZNE": "Sorgho",
    "ZNF": "Alpiste",
    "ZNG": "Millet commun",
    "ZNP": "Chou chinois",
    "ZOC": "Mélange chasse",
    "ZOD": "Pois chiche",
    "ZOE": "Rhubarbe",
    "ZOF": "Ricin",
    "ZOG": "Autres aromatiques et médicinales",
    "ZOH": "Autres ornementales",
    "ZOI": "Autre potagères",
    "ZOJ": "Espèces diverses"
  },
  "crop_combined": {
    "ZCSZLD": "Maïs grain",
    "ZCSZLE": "Maïs semences",
    "ZCSZLF": "Maïs fourrage",
    "ZCSZLL": "Maïs doux",
    "ZDHZMUZFA": "Escourgeon 6 rangs Printemps",
    "ZDHZMUZFB": "Escourgeon 6 rangs hiver",
    "ZDHZMVZFA": "Orge 2 rangs Printemps",
    "ZDHZMVZFB": "Orge 2 rangs Hiver"
  },
  "other_codes": {
    "A17": "Surface de la parcelle culturale",
    "A18": "Surface potentiellement épandable Fientes",
    "A19": "Surface irrigable",
    "A22": "Surface cadastrale",
    "A28": "Surface potentiellement épandable Fumier",
    "A38": "Surface potentiellement épandable Lisier",
    "A39": "Surface de la parcelle cadastrale",
    "A40": "Surface administrative de l'îlot",
    "AAA12": "Caractéristiques techniques du lot de produit récolté",
    "AAA13": "Caractéristiques techniques du produit récolté",
    "AAA14": "Origine de la composition ( Effluent)",
    "AAA15": "Table de référence",
    "AAA16": "Calcul logiciel",
    "AAA17": "Saisie logiciel",
    "AAA18": "Analyse",
    "AAA19": "Inconnue",
    "AAA21": "Parcelle ou zone traitée",
    "AAA22": "Parcelle non traitée",
    "AAA23": "Parcelle labourée",
    "AAA24": "Parcelle non labourée",
    "AAA25": "Bordure de champ",
    "AAA26": "Proximité de haies",
    "AAA27": "Proximité de bandes enherbées",
    "AAA28": "Proximité de jachère",
    "AAA29": "Proximité de cours d'eau",
    "AAA30": "Parcelle témoin",
    "AAA32": "Agriculture intégrée",
    "AAA33": "Agriculture biologique",
    "AAA34": "Agro foresterie",
    "AAA36": "Reliquat sortie Hiver",
    "AAA37": "Caractéristiques techniques de l'intrant",
    "AAA38": "Débit de chantier (temps pour réaliser l'intervention sur 1 ha)",
    "AAB50": "Surface observée",
    "AAB51": "Point d'observation",
    "AAT00": "Bouturage",
    "AAT01": "Distançage",
    "AAT02": "Eboutonnage",
    "AAT03": "Effleurage",
    "AAT04": "Empotage",
    "AAT05": "Entretien de nichoirs / gîtes",
    "AAT06": "Entretien des aménagements paysagers",
    "AAT07": "Fauche des drageons",
    "AAT08": "Gestion d'animaux pour la gestion des bioagresseurs",
    "AAT09": "Greffage",
    "AAT10": "Manipulation de protection anti-grêle",
    "AAT11": "Manipulation de protection anti-insecte mono-parcelle",
    "AAT12": "Manipulation de protection anti-insecte mono-rang",
    "AAT13": "Manipulation de protection anti-pluie",
    "AAT14": "Nettoyage de plantes",
    "AAT15": "Pincement",
    "AAT16": "Préparation d'extraits végétaux",
    "AAT17": "Relevé de piègeage massif",
    "AAT18": "Relevé de pièges campagnols",
    "AAT19": "Relevé de pièges monitoring",
    "AAT20": "Rempotage / repiquage",
    "AAT21": "Repiquage",
    "AAT22": "Suppression des organes contaminés",
    "AAT23": "Surfaçage",
    "AAT24": "Taille des racines",
    "AAT25": "Tuteurage",
    "AAT26": "Utilisation d'OAD",
    "ABC00": "Température",
    "ABC01": "Vitesse du vent",
    "ABC02": "Précipitations",
    "ABC03": "Inondations",
    "ABD01": "Préconisé",
    "ABD02": "Pas de traitement préconisé",
    "ABE00": "Surface non épandable",
    "ABE01": "Zone infestée",
    "ABE02": "Surface travaillée",
    "ABE03": "Zone de traitement autorisée",
    "ABE04": "Autre surface",
    "ABE05": "Surface de la parcelle pérenne",
    "ABE06": "Surface potentiellement épandable minérale",
    "ABF00": "Non calcaire (0 à 5%)",
    "ABF01": "Calcaire (>5%)",
    "ABF02": "Argileux (>30% A ou >25% A et >55%S)",
    "ABF03": "Limoneux (<55% S et <18% A)",
    "ABF04": "Limon-argileux (<55% S et 18%<A<35%)",
    "ABF05": "Sableux (>55% S et <25% A)",
    "ABF06": "Limono-sableux (15%<S<55% et <18% A)",
    "ABF07": "Sablo-limoneux (>55% S et <15% A)",
    "ABF08": "Non caillouteux (<5%)",
    "ABF09": "Caillouteux (>15%)",
    "ABF10": "Peu caillouteux (5-15%)",
    "ABF12": "hydromorphe (<60cm)",
    "ABF13": "non hydromorphe",
    "ABF14": "drainé",
    "ABG02": "Classe Calcaire",
    "ABG03": "Classe de textures",
    "ABG04": "Classe Pierrosité",
    "ABG12": "Irrigable/irriguée",
    "BT": "% de Bore (B) Total",
    "CA": "% d'Oxyde de Calcium soluble dans l'eau",
    "FT": "% de Fer (Fe) Total",
    "G90": "à couper",
    "G91": "à grappes",
    "G92": "à maquereaux",
    "G93": "à mirabelles",
    "G94": "à nectarines ou brugnons",
    "G95": "à pêches",
    "G96": "à reines-claudes, quetsches",
    "G97": "allongée",
    "G98": "Amsterdam",
    "G99": "batavia",
    "GT": "% de Manganèse (Mn) Total",
    "H01": "beef = charnue",
    "H02": "beurre pommée",
    "H03": "bigarreaux",
    "H04": "botte",
    "H05": "cerise / cocktail",
    "H06": "cerises anglaises",
    "H07": "commun",
    "H08": "Daïkon = blanc",
    "H09": "de Cayenne",
    "H10": "demi longue et longues de type jersey",
    "H11": "demi-long à bout blanc",
    "H12": "des teinturiers",
    "H13": "d'Espagne",
    "H15": "fdp x rgi",
    "H16": "fe x rgi",
    "H17": "gazon",
    "H18": "Globuleux vert",
    "H19": "grande",
    "H20": "grasse",
    "H21": "Grenadille",
    "H22": "griottes",
    "H23": "Grise",
    "H24": "grosse",
    "H25": "Guignes",
    "H26": "hybride",
    "H27": "inuline",
    "H28": "japonais",
    "H29": "jaune de Hollande",
    "H30": "le rond rouge",
    "H31": "nantaise",
    "H32": "pavies",
    "H33": "Petit violet",
    "H34": "Poirée = bettes",
    "H35": "Pomme à cidre",
    "H36": "pommes de table",
    "H37": "Porte-Greffe",
    "H38": "pruneaux (prune d'ente)",
    "H39": "romaine",
    "H40": "ronde à l'unité",
    "H41": "ronde en grappe",
    "H43": "sommites graines sèches",
    "H44": "types anciens",
    "H46": "à grosses racines",
    "H47": "citrouille pâtisson",
    "H48": "musquée - de Provence - Butternut",
    "H49": "saison",
    "H50": "remontant",
    "H51": "fraisier des bois",
    "H52": "Galia",
    "H53": "cantaloup ou charentais jaunissant à maturité",
    "H54": "cantaloup ou charentais non jaunissant à maturité",
    "H55": "brodé américain",
    "H56": "d'hiver ou sans odeur (type Canari)",
    "H57": "Fleur",
    "H58": "Aromatique",
    "H59": "Bois",
    "H60": "bourgeons",
    "H61": "Cuve",
    "H62": "feuilles et fruits",
    "H63": "Fruit",
    "H64": "racines fraîches",
    "H65": "racines séchées",
    "H66": "Table",
    "H69": "Mélange",
    "H70": "enherbement non fourrager",
    "H71": "Oléifère",
    "H72": "Autre",
    "I01": "Arbousier commun",
    "I02": "Arbre à pain",
    "I03": "Aulne",
    "I04": "Bouleau",
    "I06": "Canne de provence ou roseaux à quenouilles",
    "I07": "Capucine tubéreuse",
    "I08": "Carambolier",
    "I10": "Cèdre",
    "I11": "Cerfeuil tubéreux",
    "I12": "Charme",
    "I14": "Chêne",
    "I15": "Chervis",
    "I16": "Cormier",
    "I17": "Douglas",
    "I19": "Erable",
    "I20": "Eucalyptus",
    "I21": "Flouve médicinale",
    "I22": "Frêne",
    "I23": "Gerbera",
    "I24": "Gesse Commune ou pois carré",
    "I25": "Gingembre",
    "I26": "Gombo",
    "I27": "Grenadier",
    "I28": "Guède ou pastel des teinturiers",
    "I29": "Hêtre",
    "I30": "King-grass",
    "I31": "Longanie",
    "I32": "Malanga ou chou caraïbe",
    "I33": "Manioc",
    "I34": "Mélèze",
    "I35": "Merisier",
    "I36": "Nyger",
    "I37": "Papayer",
    "I38": "Peuplier",
    "I39": "Pin",
    "I40": "Pitaya",
    "I41": "Pomme Liane ou Grenadille",
    "I42": "Ramboutan",
    "I43": "Robinier",
    "I44": "Sapin",
    "I45": "Sapotillier",
    "I46": "Saule",
    "I47": "Sequoia",
    "I48": "Yacón ou Poire de terre",
    "I49": "Buis",
    "I50": "Marronnier",
    "I51": "Laurier cerise",
    "I52": "Platane commun",
    "I53": "Palmier éventail de Californie",
    "I54": "Palmier bleu",
    "I55": "Palmier nain",
    "I56": "Palmier dattier",
    "I57": "Palmier de Chine",
    "I58": "Thuya",
    "I59": "Faux-Cyprès",
    "I60": "Cyprès commun",
    "I61": "Genévrier",
    "I62": "Epicéa",
    "I63": "Arbre de Judée",
    "I64": "Camélia",
    "I65": "Catalpa",
    "I66": "Chalef argenté",
    "I67": "Fuchsia",
    "I68": "Fusain",
    "I69": "Hibuscus althéa",
    "I70": "Laurier-rose",
    "I71": "Mahonia",
    "I72": "Mimosa",
    "I73": "Pyracantha (buisson ardent)",
    "I74": "Rhododendron",
    "I75": "Viorne",
    "I76": "Amandier de Chine",
    "I77": "Amandier nain de Chine",
    "I78": "Cerisier du Japon",
    "I79": "Cerisier à fleurs à port colonnaire",
    "I80": "Cerisier de Mandchourie",
    "I81": "Cerisier hybride à fleurs",
    "I82": "Cerisier à fleurs doubles",
    "I83": "Cerisier du Tibet",
    "I84": "Merisier à grappes blanches",
    "I85": "Merisier à grappes roses",
    "I86": "Prunier à fleurs",
    "I87": "Prunier d'ornement à feuillage pourpre",
    "I88": "Anthurium",
    "I89": "Amaryllis belladona",
    "I90": "Campanule",
    "I91": "Célosie",
    "I92": "Delphinium",
    "I93": "Giroflée ravenelle",
    "I94": "Hortensia",
    "I95": "Hibiscus sabdariffa",
    "I96": "Lisianthus",
    "I97": "Muflier",
    "I98": "Pivoine",
    "I99": "Rosier multiflore",
    "J03": "Tulipe",
    "J04": "Cultures tropicales",
    "J05": "Divers",
    "J06": "CIPAN potentiel",
    "J07": "Cultures fourragères/Prairie/ Pelouse/ Gazon",
    "J08": "Sylviculture",
    "J10": "Grandes cultures",
    "J11": "PPAM",
    "J12": "Cultures dédiées à la production de biomasse",
    "J13": "Cornus",
    "J14": "Cotoneaster",
    "J15": "Euonymus",
    "J17": "Ilex",
    "J18": "Lagerstroemia",
    "J19": "Ligustrum",
    "J20": "Magnolia",
    "J21": "Osmanthus",
    "J22": "Photinia",
    "J23": "Pittosporum",
    "J24": "Santoline",
    "J25": "Spiraea",
    "J26": "Cupressocyparis",
    "J27": "Begonia",
    "J28": "Bidens",
    "J29": "Calibrachoa",
    "J30": "Coleus",
    "J31": "Coreopsis",
    "J32": "Cyclamen",
    "J33": "Diascia",
    "J34": "Dipladénia",
    "J35": "Gazania",
    "J37": "Impatiens",
    "J38": "Lantana",
    "J40": "Osteospermum",
    "J41": "Pelargonium",
    "J42": "Pelargonium grandiflorum",
    "J43": "Pelargonium hortorum",
    "J44": "Pelargonium peltatum",
    "J45": "Petunia",
    "J46": "Poinsettia",
    "J47": "Rudbeckia",
    "J48": "Viola",
    "J49": "Pâquerette",
    "J50": "Impatiens walleriana",
    "J51": "Impatiens Nouvelle Guinée",
    "J52": "Mélange Gazon",
    "J53": "Heuchère",
    "J54": "Tulipier de Virginie",
    "J55": "Magnolia grandiflora",
    "J56": "Magnolia soulangeana",
    "J57": "Quinoa",
    "KT": "% d'Oxyde de Potassium (K2O) total",
    "LT": "% deMolybdène (Mo) total",
    "MT": "% d'oxyde de magnésium total",
    "NJ": "% d'azote (N) nitrique",
    "NL": "% d'azote (N) ammoniacal",
    "NM": "% d'azote (N) uréique",
    "NT": "% d'azote (N) total",
    "OT": "% de Cobalt (Co) total",
    "PT": "% d'anhydride phosphorique (P2O5) total",
    "SEA": "Arrachage",
    "SEB": "Binage",
    "SEC": "Broyage cailloux",
    "SED": "Buttage",
    "SEE": "Déchaumage",
    "SEF": "Décompactage",
    "SEG": "Défanage",
    "SEH": "Andainage",
    "SEI": "Enfouissement",
    "SEJ": "Ensilage",
    "SEK": "Epandage organique",
    "SEL": "Fauchage",
    "SEM": "Fertilisation",
    "SEN": "Hersage",
    "SEO": "Irrigation",
    "SEP": "Labour",
    "SEQ": "Moisson",
    "SER": "Récolte",
    "SES": "Roulage",
    "SET": "Semis classique",
    "SEU": "Semis direct",
    "SEV": "Sous solage",
    "SEW": "Plantation",
    "SEX": "Traitement phytosanitaire",
    "SFA": "Epuration",
    "SFB": "Paillage",
    "SFC": "Castration",
    "SFD": "Triage au champ",
    "SFE": "Pressage",
    "SFG": "Billonnage",
    "SFH": "Solarisation",
    "SFI": "Bâchage",
    "SFJ": "Tamisage et/ou Epierrage",
    "SFK": "Broyage des résidus",
    "SO": "% d'oxyde de sodium (Na2O) soluble dans l'eau",
    "ST": "% d'anhydride sulfurique (SO3) total",
    "T35": "nombre de mètres linéaires (unité)",
    "T36": "nombre de mètres linéaires/ha",
    "T37": "Volume de bouillie (intrant)",
    "T88": "Repousses pois",
    "T90": "Autre graminée",
    "T91": "Autre crucifère",
    "T92": "Autre légumineuse",
    "T93": "Autre melange",
    "TPA": "Type d'agriculture pratiquée",
    "UT": "% de cuivre (Cu) total",
    "V07": "nord",
    "V08": "sud",
    "V09": "est",
    "V10": "ouest",
    "V11": "nord est",
    "V12": "sud est",
    "V13": "nord ouest",
    "V14": "sud ouest",
    "V15": "nord-nord est",
    "V16": "nord-nord ouest",
    "V17": "sud-sud est",
    "V18": "sud-sud ouest",
    "V19": "est -sud est",
    "V20": "est-nord est",
    "V21": "ouest-sud ouest",
    "V22": "ouest-nord ouest",
    "V23": "plane",
    "V24": "nord - sud",
    "V25": "est - ouest",
    "V26": "nord est - sud ouest",
    "V27": "nord ouest - sud est",
    "V28": "sud-sud est/ nord -nord ouest",
    "V29": "sud-sud ouest/ nord- nord est",
    "V30": "est-nord est / ouest-sud ouest",
    "V31": "ouest-nord ouest/est-sud est",
    "V32": "parallèle",
    "V33": "perpendiculaire",
    "V34": "oblique",
    "V46": "Vin",
    "V47": "Raisin de table",
    "V48": "Raisin sec",
    "V49": "Jus de raisin",
    "V50": "alcool de distillerie",
    "V51": "Vinaigre",
    "V52": "Autre destination",
    "V70": "Travail (Labour, désherbage mécanique, ...)",
    "V71": "Désherbage chimique",
    "V72": "Enherbement semé",
    "V73": "Enherbement Naturel Maîtrisé",
    "V74": "Apport de Mulch (Ecorces, Broyat, …)",
    "V75": "1 rg sur 2",
    "V76": "1 rg sur 3",
    "V77": "2 rgs sur 3",
    "V78": "total",
    "V85": "Aménagement foncier",
    "V86": "Désinfection",
    "V87": "Surgreffage",
    "V88": "Piquetage/Marquants",
    "V89": "Dévitalisation",
    "V90": "Installation de protection",
    "V91": "Observation carences",
    "V92": "Complantation/recépage/marcotage",
    "V93": "Décavaillonage",
    "V94": "Cavaillonage",
    "V95": "Désherbage",
    "V96": "Travail de surface (binage, hersage, griffage, ...)",
    "V97": "Palissage (mise en place et entretien)",
    "V98": "Tonte",
    "V99": "Brulage enherbement (estivage, ..)",
    "W01": "Taille (badigeonnage compris)",
    "W02": "Pré -taille",
    "W03": "Broyage des bois de taille",
    "W04": "Tirage et/ou Brûlage des bois",
    "W05": "Liage/Attachage/Pliage",
    "W06": "Pliage (à la taille)",
    "W07": "Relevage, accolage",
    "W08": "Egourmandage (=epamprage)",
    "W09": "Rognage / Ecimage",
    "W10": "Ebourgeonnage",
    "W11": "Effeuillage",
    "W12": "Eclaircissage",
    "W13": "Vendange en vert (grapillonnage, ...)",
    "W14": "Taille en vert",
    "W15": "Rajout de terre",
    "W16": "Lutte biologique",
    "W18": "Protection climatique",
    "W19": "Vendange",
    "W20": "Contrôle maturité",
    "W21": "Observation ravageurs et maladies",
    "W22": "Autres observations",
    "W23": "Fanage",
    "W24": "Transport",
    "W25": "Pâturage",
    "W26": "Brûlage des résidus",
    "W27": "Engaignage",
    "W28": "Haubanage",
    "W78": "Raisin de table",
    "W79": "Raisin de cuve",
    "W80": "Raisin apyrène",
    "W81": "Double fin",
    "ZAA": "Agriculture raisonnée",
    "ZAB": "Certification ISO 9000",
    "ZAC": "Certification ISO 14000",
    "ZAD": "Référentiel Quali'terre",
    "ZAE": "Référentiel FARRE",
    "ZCT": "Mélange Graminées",
    "ZD1": "Type de sol",
    "ZD2": "Classe Profondeur (profondeur d'apparition du sous-sol?)",
    "ZD3": "Classe hydromorphie",
    "ZD4": "Type de sous-sol",
    "ZD5": "Acidité du sol",
    "ZD6": "Drainage",
    "ZD7": "Engagements",
    "ZE8": "Amendement organique analysé",
    "ZE9": "Amendement organique non analysé",
    "ZEO": "pâturée",
    "ZEP": "fauchée",
    "ZEQ": "pâturée et fauchée",
    "ZER": "Fibre",
    "ZES": "Oléagineux",
    "ZET": "papeterie",
    "ZEU": "brun",
    "ZEV": "virginie",
    "ZEW": "burley",
    "ZEX": "textile",
    "ZEY": "Parcelle culturale redécoupée",
    "ZF1": "Amendement calcaire",
    "ZF7": "Récolte",
    "ZF8": "Travail du sol",
    "ZF9": "Autres travaux agricoles",
    "ZFD": "Non renseigné",
    "ZFE": "Limon",
    "ZFF": "Limon argileux",
    "ZFG": "Argileux",
    "ZFH": "Argile lourde (sol a plus de 50 % d'argile)",
    "ZFI": "Argilo-limoneux",
    "ZFJ": "Argilo-calcaire",
    "ZFK": "Argile limono-sableuse",
    "ZFL": "Argilo-sableux",
    "ZFM": "Sable",
    "ZFN": "Limon sableux",
    "ZFO": "Limon sablo-argileux",
    "ZFP": "Limoneux",
    "ZFQ": "Limono-argileux",
    "ZFR": "Limono-sableux",
    "ZFS": "Sablo-argileux",
    "ZFT": "Sablo-limoneux",
    "ZFU": "sables limono-argileux",
    "ZFV": "Argile à silex",
    "ZFW": "Craie",
    "ZFX": "Terre de craie",
    "ZFY": "Sol organique (y compris tourbe)",
    "ZFZ": "Calcaire fissuré",
    "ZG1": "Indicateur de décision",
    "ZG7": "Intrant",
    "ZG8": "Traitements spéciaux",
    "ZGA": "Dalle calcaire",
    "ZGB": "Très acide",
    "ZGC": "Acide",
    "ZGD": "Neutre",
    "ZGE": "Basique",
    "ZGF": "Limon non battant",
    "ZGG": "Superficiel",
    "ZGH": "Moyen (limon...)",
    "ZGI": "Profond",
    "ZGJ": "Cailloux",
    "ZGK": "Granit",
    "ZGL": "Argile verte",
    "ZGM": "Marne",
    "ZGN": "Contrat de production",
    "ZGP": "Certification agriculture biologique",
    "ZGQ": "Contrat de production sous Agriconfiance",
    "ZGR": "Charte de production Céréales",
    "ZGS": "Label",
    "ZGT": "Certificat de conformité produit",
    "ZGU": "Cahier des charges d'agriculture durable",
    "ZGV": "Charte de l'agriculture paysanne",
    "ZHA": "Mesures agro-environnementales",
    "ZHB": "Référentiel GLOBAL GAP",
    "ZHC": "Norme Production \"Pomme de terre\" NF V25 111",
    "ZHD": "Contrat de production Semences/Plants Certifiés",
    "ZHE": "Autres opérations ou contrat",
    "ZHI": "Résidus enfouis broyés",
    "ZHJ": "Schistes",
    "ZHK": "Limon argilo-sableux",
    "ZHP": "Pluies",
    "ZHQ": "Orages",
    "ZHR": "Grêle",
    "ZHS": "Gel",
    "ZHT": "Sécheresse",
    "ZHU": "Chaleur",
    "ZHV": "Météo sans incidence",
    "ZHW": "Vent",
    "ZJH": "Produit principal (grain, racine, tubercule)",
    "ZJI": "Coproduit (paille)",
    "ZK2": "Evènement réalisé",
    "ZK9": "Objectif de rendement",
    "ZLB": "Plan Environnement Agriculture",
    "ZLC": "Autre type d'agriculture",
    "ZLD": "Grain(es)",
    "ZLE": "Semence / Porte graine",
    "ZLF": "Fourrager / Fourrage",
    "ZLG": "Biscuit",
    "ZLH": "Meunier",
    "ZLI": "Ethanol",
    "ZLJ": "Résidus exportés",
    "ZLK": "Résidus brûlés",
    "ZLL": "doux",
    "ZLM": "Noir(e)",
    "ZLN": "Blanche",
    "ZLO": "Plant (générique)",
    "ZLP": "Fécule",
    "ZLQ": "Frais",
    "ZLR": "Consommation",
    "ZLS": "Transformation",
    "ZLT": "permanente",
    "ZLU": "temporaire",
    "ZLW": "Diester",
    "ZMP": "Potager",
    "ZMQ": "Branches",
    "ZMR": "Rave",
    "ZMS": "Plan de fumure",
    "ZMU": "6 rangs",
    "ZMV": "2 rangs",
    "ZMW": "Primeur",
    "ZMX": "Analyse de sol",
    "ZMY": "Analyse de plantes cultivées",
    "ZMZ": "Adventices",
    "ZNA": "Destruction (générique)",
    "ZNB": "Conditions météorologiques",
    "ZNC": "Autres mesures OAD",
    "ZNH": "Frisé",
    "ZNI": "Sec",
    "ZNJ": "Protéagineux",
    "ZNK": "Cabu",
    "ZNO": "de milan",
    "ZNQ": "Scarole",
    "ZNR": "à feuilles = sauvage améliorée",
    "ZNS": "Industrie",
    "ZNT": "sec frais",
    "ZNU": "sec conserve",
    "ZNV": "vert frais",
    "ZNW": "vert conserve",
    "ZNX": "pop-corn",
    "ZOB": "Lavandin",
    "ZPA": "Déshydraté",
    "ZPB": "Biomasse",
    "ZPC": "Bio énergie",
    "ZPD": "Chimie verte",
    "ZRA": "Tours d'eau",
    "ZRB": "Bilan hydrique",
    "ZRC": "Bilan fertilisation",
    "ZRD": "Réglementation",
    "ZRE": "Argile sablo-limoneuse",
    "ZSD": "Résidus enfouis non broyés",
    "ZT": "% de zinc (Zn) total",
    "ZTA": "Destruction des mâles (maïs)",
    "ZTB": "Fermeture du silo",
    "ZTC": "Autre type de travail",
    "ZUA": "Zone vulnérable",
    "ZUB": "Zone d'excédent structurel",
    "ZUC": "Zone d'actions complémentaires",
    "ZUD": "Site Natura 2000",
    "ZUE": "Zone d'érosion (arrêté préfectotal)",
    "ZUF": "Périmètre de protection de captage",
    "ZUG": "Parcelle ayant reçu des boues de station d'épuration",
    "ZUH": "Zone d'actions renforcées",
    "ZUI": "Appellation d’origine contrôlée ou protégée (AOC ou AOP)",
    "ZUJ": "Indication géographique protégée (IGP)",
    "ZUK": "Spécialité traditionnelle garantie (STG)",
    "ZUL": "Charte de production du maïs doux ARVALIS - Institut du végétal/IRTAC",
    "ZUM": "Charte de production des protéagineux ARVALIS - Institut du végétal / IRTAC",
    "ZUN": "Charte qualité maïs grand sud ouest",
    "ZUO": "Norme Agriconfiance NF V01 – 007 (environnement)."
  }
};

/**
 * Find label for a code by searching all categories
 * @param {string} code - The AEE code (e.g., 'ZIV', 'SCA')
 * @returns {string|undefined} The label or undefined if not found
 */
export function findLabel(code) {
  for (const category of Object.values(AEE_CODES)) {
    if (category[code]) {
      return category[code];
    }
  }
  return undefined;
}

/**
 * Get label for a specific category
 * @param {string} category - Category name (e.g., 'input_nature', 'organic_input')
 * @param {string} code - The AEE code (e.g., 'ZIV', 'SCA')
 * @returns {string|undefined} The label or undefined if not found
 */
export function getLabel(category, code) {
  return AEE_CODES[category]?.[code];
}

/**
 * Get all codes for a category
 * @param {string} category - Category name
 * @returns {Object} Object mapping codes to labels
 */
export function getCodes(category) {
  return AEE_CODES[category] || {};
}

export default AEE_CODES;
